### ISSUE TITLE
the loader only got rendered when react-data-fetching got rendered, never show up when reload data

### ISSUE THREAD

**Issue by chaiyilin** [CharlesMangwa/react-data-fetching#11]

**Comment by CharlesMangwa** [comment]
Hi @chaiyilin! Thanks for letting me know!

I think the problem might come from [here](https://github.com/CharlesMangwa/react-data-fetching/blob/master/modules/Fetch.js#L107-L112): I forgot to set `this._isLoaded = false` so that the loader is displayed again [here](https://github.com/CharlesMangwa/react-data-fetching/blob/master/modules/Fetch.js#L315-L316).

If you could fix this issue and send a PR that would be great! 💖✨
