### ISSUE TITLE
Can’t build with create-react-app

### ISSUE THREAD

**Issue by Madumo** [CharlesMangwa/react-data-fetching#9]
It appears that CRA cannot minify the esm version, and [recommend libraries to be published in ES5](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-data-fetching/esm/react-data-fetching.js:1003

Read more here: http://bit.ly/2tRViJ9
```

**Comment by CharlesMangwa** [comment]
Hi @Madumo! Thanks for the heads up!

After a few minutes of digging on GitHub I found similar issues (https://github.com/Turfjs/turf/issues/1133) and the fix seems to be quite simple: IINM we just have to add [`rollup-plugin-buble`](https://buble.surge.sh/guide/) to implement ES5 compilation ([example here](https://github.com/DenisCarriere/turf-jsts/blob/master/rollup.config.js)) in the project's [rollup config](https://github.com/CharlesMangwa/react-data-fetching/blob/master/scripts/config.js#L11).

It would also be great to test it with `react-scripts build` to make sure it fixes this issue ([like here](https://github.com/DenisCarriere/turf-jsts/blob/master/package.json#L59)).

If you can handle this and send a PR that would be awesome! ✨ Otherwise, I'll try to fix it this weekend or the next one.

**Comment by Madumo** [comment]
Sure thing! I'll provide a PR shortly 😊

Also: i found that with create-react-app >= 2.0.0, [it won't be a problem anymore](https://github.com/facebook/create-react-app/pull/3776).

**Comment by CharlesMangwa** [comment]
Oh cool, appreciate it! Let me know if you need anything while doing so.

Glad to read that!

**Comment by gaearon** [comment]
https://reactjs.org/blog/2018/10/01/create-react-app-v2.html
